### ISSUE TITLE
build failing for wasm arch

### ISSUE THREAD

**Issue by storybehind** [gen2brain/heic#3]
Executing command `CGO_ENABLED=0 GOOS=js GOARCH=wasm go build ./...` at the root folder of this project produces below error:

`# github.com/gen2brain/heic
./decode_dynamic.go:115:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:116:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:117:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:118:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:119:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:120:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:121:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:122:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:123:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:124:9: undefined: purego.RegisterLibFunc
./decode_dynamic.go:124:9: too many errors`

go version:
`go version go1.22.0 linux/amd64`

**Comment by gen2brain** [comment]
Fixed in https://github.com/gen2brain/heic/commit/d21a3006d72746c96d2bf5519e5a246f0f504eaa.
