### ISSUE TITLE
wasm error: out of bounds memory access

### ISSUE THREAD

**Issue by tucocsa** [gen2brain/heic#5]
If I convert one image it works great, but
when I try to convert multiple images in a row I get this error:

`wasm error: out of bounds memory access\nwasm stack trace:\n\t.$1551(i32,i32,i32) i32\n\t.$9(i32,i32,i32,i32,i32,i32,i32,i32,i32) i32`

is it possible to fix it? 

macos `go version go1.22.5 darwin/amd64`

**Comment by eduardo-mior** [comment]
I have the same problem even though I'm trying to convert just one image

**Comment by eduardo-mior** [comment]
[image.zip](https://github.com/user-attachments/files/17204313/image.zip)

This photo was taken directly from my iPhone camera and when I tried to convert it I got the following error
```
wasm error: out of bounds memory access
wasm stack trace:
        .$1551(i32,i32,i32) i32
        .$9(i32,i32,i32,i32,i32,i32,i32,i32,i32) i32
```

go version go1.22.6 windows/amd64

**Comment by gen2brain** [comment]
@eduardo-mior Can you tell me if you are using iOS 18?

**Comment by eduardo-mior** [comment]
@gen2brain No, this photo was taken using an iPhone 7, iOS 15.8

**Comment by eduardo-mior** [comment]
@gen2brain Can I contribute any more test images or files?

**Comment by gen2brain** [comment]
Thank you, when I find time I will check this.

**Comment by gen2brain** [comment]
This is fixed in https://github.com/gen2brain/heic/commit/cde567df8577087abf8386c4da9d7dee90ae771e. Now it will instantiate the module on every invocation, it will use more resources (more allocations) but can be safely called concurrently.

**Comment by eduardo-mior** [comment]
I did some tests here and everything seems to be working! Congratulations on the work, you're awesome.
